#!/bin/bash
CWHITE="\x1B[0m"
CRED="\x1B[31m"
CGREEN="\x1B[32m"
CYELLOW="\x1B[33m"

function cleanup {
  kill -9 %1
  popd &> /dev/null
  echo -e "\n${CRED}Killing MGView server.${CWHITE}"
  echo -e "${CYELLOW}Existing MGView tabs open in Chrome are now inactive.${CWHITE}"
}

#####################
#### Entry point ####
#####################

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Go up a level
pushd $DIR/.. &> /dev/null

echo -e "${CYELLOW}Starting MGView $(cat ${DIR}/bin/VERSION)${CWHITE}"
echo -e "${CRED}Server is running. Open your browser and type localhost:8000 in the address bar.${CWHITE}"
echo -e "${CRED}Press Ctrl+C to quit.${CWHITE}"

python -m SimpleHTTPServer 8000 &
sleep 0.5

google-chrome localhost:8000

if [ $? -ne 0 ]; then
  echo -e "${CRED}Chrome failed to start. Try manually starting Chrome, then run this script again.${CWHITE}"
  kill -9 %1
  popd &> /dev/null
  exit -1
fi

trap cleanup EXIT
while read -n 1 -s line
do
  echo -e "${CRED}Press Ctrl+C to quit.${CWHITE}"
done

