#!/bin/bash

# Entry point
pushd ..

echo -e "\e[1;33mStarting MGView $(cat MGView/bin/VERSION)\e[00m"
echo -e "\e[1;31mServer is running. Open chrome and go to localhost:8000 in the address bar.\e[00m"
echo -e "\e[1;31mPress Ctrl+C to quit.\e[00m"

python -m SimpleHTTPServer 8000

popd
